using System;
using System.Collections.Generic;
using RealmRaiders.Modules.InfernalDefenseLayouts;
using RealmRaiders.Modules.InfernalEncounters;
using RealmRaiders.Modules.RealmLayoutContracts;

namespace RealmRaiders.Modules.InfernalFirstExpansionContent
{
    public enum InfernalFirstExpansionContentLookupStatus { Found, LayoutIdInvalid, SocketIdInvalid, LayoutUnknown, SocketUnknown, SocketNotFirstAuthored, CatalogueInvalid }
    public enum InfernalFirstExpansionContentValidationIssue { RecipeMissing, CatalogueCardinalityInvalid, CatalogueOrderMismatch, LayoutIdInvalid, SocketIdInvalid, SourceNodeIdInvalid, SiteIdInvalid, SiteSignatureInvalid, LayoutIdDuplicate, SiteIdDuplicate, SiteSignatureDuplicate, LayoutUnknown, FirstSocketMismatch, SourceNodeMismatch, HostileCardinalityInvalid, HostileMissing, HostileContentUnsupported, HostileOffsetInvalid, HazardContentUnsupported, HazardOffsetInvalid, HazardSemanticsInvalid, CueInvalid, ExactFactsMismatch, HostileOrderMismatch }

    public sealed class InfernalExpansionHostilePlacement
    {
        public InfernalExpansionHostilePlacement(string contentId, float localX, float localZ) { ContentId = contentId; LocalX = localX; LocalZ = localZ; }
        public string ContentId { get; } public float LocalX { get; } public float LocalZ { get; }
    }
    public sealed class InfernalExpansionHazardPlacement
    {
        public InfernalExpansionHazardPlacement(string contentId, float localX, float localZ, bool isBypassable, bool isNonBlocking) { ContentId = contentId; LocalX = localX; LocalZ = localZ; IsBypassable = isBypassable; IsNonBlocking = isNonBlocking; }
        public string ContentId { get; } public float LocalX { get; } public float LocalZ { get; } public bool IsBypassable { get; } public bool IsNonBlocking { get; }
    }
    public sealed class InfernalFirstExpansionContentRecipe
    {
        public InfernalFirstExpansionContentRecipe(string layoutId, string socketId, string sourceNodeId, string siteId, string siteName, string siteSignature, IReadOnlyList<InfernalExpansionHostilePlacement> hostiles, InfernalExpansionHazardPlacement hazard, string cue)
        { LayoutId=layoutId; SocketId=socketId; SourceNodeId=sourceNodeId; SiteId=siteId; SiteName=siteName; SiteSignature=siteSignature; Hostiles=Snapshot(hostiles); Hazard=hazard; Cue=cue; }
        public string LayoutId { get; } public string SocketId { get; } public string SourceNodeId { get; } public string SiteId { get; } public string SiteName { get; } public string SiteSignature { get; } public IReadOnlyList<InfernalExpansionHostilePlacement> Hostiles { get; } public InfernalExpansionHazardPlacement Hazard { get; } public string Cue { get; }
        private static IReadOnlyList<T> Snapshot<T>(IReadOnlyList<T> source) { if(source==null)return Array.AsReadOnly(Array.Empty<T>()); var copy=new T[source.Count]; for(var i=0;i<copy.Length;i++)copy[i]=source[i]; return Array.AsReadOnly(copy); }
    }
    public sealed class InfernalFirstExpansionContentLookupResult { internal InfernalFirstExpansionContentLookupResult(InfernalFirstExpansionContentLookupStatus status, InfernalFirstExpansionContentRecipe recipe){Status=status;Recipe=recipe;} public InfernalFirstExpansionContentLookupStatus Status{get;} public InfernalFirstExpansionContentRecipe Recipe{get;} public bool Found=>Status==InfernalFirstExpansionContentLookupStatus.Found&&Recipe!=null; }
    public sealed class InfernalFirstExpansionContentValidationResult { internal InfernalFirstExpansionContentValidationResult(IReadOnlyList<InfernalFirstExpansionContentValidationIssue> issues){Issues=Copy(issues);} public IReadOnlyList<InfernalFirstExpansionContentValidationIssue> Issues{get;} public bool IsValid=>Issues.Count==0; private static IReadOnlyList<T> Copy<T>(IReadOnlyList<T> source){if(source==null)return Array.AsReadOnly(Array.Empty<T>());var copy=new T[source.Count];for(var i=0;i<copy.Length;i++)copy[i]=source[i];return Array.AsReadOnly(copy);} }

    public static class StarterInfernalFirstExpansionContent
    {
        private const float MaximumAbsoluteOffset = 2.5f;
        public static InfernalFirstExpansionContentRecipe AshenPackVent { get; } = Recipe(StarterInfernalDefenseLayouts.AshenSpurId,"ashen.west-vent","ashen.hellhound","realmraiders.infernal-expansion.ashen-pack-vent","Ashen Pack Vent","ashen-pack-vent",new[]{Hostile(StarterInfernalRaidPacingCatalogue.HellhoundArchetypeId,-1.8f,0.8f),Hostile(StarterInfernalRaidPacingCatalogue.HellhoundArchetypeId,1.8f,1.2f)},null,"TWO HELLHOUNDS GUARD THE ASHEN VENT.");
        public static InfernalFirstExpansionContentRecipe CinderSnareVent { get; } = Recipe(StarterInfernalDefenseLayouts.CinderForkId,"cinder.north-vent","cinder.hellhound","realmraiders.infernal-expansion.cinder-snare-vent","Cinder Snare Vent","cinder-snare-vent",new[]{Hostile(StarterInfernalRaidPacingCatalogue.HellhoundArchetypeId,0f,1.3f)},Hazard(StarterInfernalRaidPacingCatalogue.FlameTrapContentId,0f,-0.4f,true,true),"A HELLHOUND GUARDS THE CINDER SNARE.");
        public static InfernalFirstExpansionContentRecipe BruteKilnVent { get; } = Recipe(StarterInfernalDefenseLayouts.EmberCircuitId,"ember.west-vent","ember.hellhound","realmraiders.infernal-expansion.brute-kiln-vent","Brute Kiln Vent","brute-kiln-vent",new[]{Hostile(StarterInfernalRaidPacingCatalogue.InfernalBruteArchetypeId,0f,1.5f)},null,"AN INFERNAL BRUTE HOLDS THE EMBER VENT.");
        public static IReadOnlyList<InfernalFirstExpansionContentRecipe> All { get; }=Array.AsReadOnly(new[]{AshenPackVent,CinderSnareVent,BruteKilnVent});
        public static InfernalFirstExpansionContentLookupResult FindExact(string layoutId,string socketId)
        { if(!Stable(layoutId))return Reject(InfernalFirstExpansionContentLookupStatus.LayoutIdInvalid);if(!Stable(socketId))return Reject(InfernalFirstExpansionContentLookupStatus.SocketIdInvalid);if(!Validate(All).IsValid)return Reject(InfernalFirstExpansionContentLookupStatus.CatalogueInvalid);var layout=StarterInfernalDefenseLayoutResolver.ResolveExact(layoutId);if(!layout.HasLayout)return Reject(InfernalFirstExpansionContentLookupStatus.LayoutUnknown);var first=layout.Layout.ExpansionSockets.Count==0?null:layout.Layout.ExpansionSockets[0];if(first==null)return Reject(InfernalFirstExpansionContentLookupStatus.CatalogueInvalid);if(!string.Equals(first.SocketId,socketId,StringComparison.Ordinal))return Reject(Contains(layout.Layout,socketId)?InfernalFirstExpansionContentLookupStatus.SocketNotFirstAuthored:InfernalFirstExpansionContentLookupStatus.SocketUnknown);foreach(var recipe in All)if(Matches(recipe,layoutId,socketId))return new InfernalFirstExpansionContentLookupResult(InfernalFirstExpansionContentLookupStatus.Found,recipe);return Reject(InfernalFirstExpansionContentLookupStatus.CatalogueInvalid); }
        public static InfernalFirstExpansionContentValidationResult Validate(IReadOnlyList<InfernalFirstExpansionContentRecipe> recipes)
        {var issues=new List<InfernalFirstExpansionContentValidationIssue>();if(recipes==null||recipes.Count!=3)Add(issues,InfernalFirstExpansionContentValidationIssue.CatalogueCardinalityInvalid);var layouts=new HashSet<string>(StringComparer.Ordinal);var sites=new HashSet<string>(StringComparer.Ordinal);var signatures=new HashSet<string>(StringComparer.Ordinal);if(recipes!=null){foreach(var recipe in recipes)ValidateRecipe(recipe,layouts,sites,signatures,issues);if(recipes.Count==All.Count)for(var i=0;i<All.Count;i++)if(recipes[i]==null||!Matches(recipes[i],All[i].LayoutId,All[i].SocketId))Add(issues,InfernalFirstExpansionContentValidationIssue.CatalogueOrderMismatch);}return new InfernalFirstExpansionContentValidationResult(issues);}
        private static void ValidateRecipe(InfernalFirstExpansionContentRecipe r,ISet<string> layouts,ISet<string> sites,ISet<string> signatures,ICollection<InfernalFirstExpansionContentValidationIssue> issues)
        {if(r==null){Add(issues,InfernalFirstExpansionContentValidationIssue.RecipeMissing);return;} Valid(r.LayoutId,InfernalFirstExpansionContentValidationIssue.LayoutIdInvalid,issues);Valid(r.SocketId,InfernalFirstExpansionContentValidationIssue.SocketIdInvalid,issues);Valid(r.SourceNodeId,InfernalFirstExpansionContentValidationIssue.SourceNodeIdInvalid,issues);Valid(r.SiteId,InfernalFirstExpansionContentValidationIssue.SiteIdInvalid,issues);Valid(r.SiteSignature,InfernalFirstExpansionContentValidationIssue.SiteSignatureInvalid,issues);if(Stable(r.LayoutId)&&!layouts.Add(r.LayoutId))Add(issues,InfernalFirstExpansionContentValidationIssue.LayoutIdDuplicate);if(Stable(r.SiteId)&&!sites.Add(r.SiteId))Add(issues,InfernalFirstExpansionContentValidationIssue.SiteIdDuplicate);if(Stable(r.SiteSignature)&&!signatures.Add(r.SiteSignature))Add(issues,InfernalFirstExpansionContentValidationIssue.SiteSignatureDuplicate);var layout=StarterInfernalDefenseLayoutResolver.ResolveExact(r.LayoutId);if(!layout.HasLayout)Add(issues,InfernalFirstExpansionContentValidationIssue.LayoutUnknown);else{var first=layout.Layout.ExpansionSockets.Count==0?null:layout.Layout.ExpansionSockets[0];if(first==null||!string.Equals(first.SocketId,r.SocketId,StringComparison.Ordinal))Add(issues,InfernalFirstExpansionContentValidationIssue.FirstSocketMismatch);else if(!string.Equals(first.NodeId,r.SourceNodeId,StringComparison.Ordinal))Add(issues,InfernalFirstExpansionContentValidationIssue.SourceNodeMismatch);}ValidateHostiles(r.Hostiles,issues);ValidateHazard(r.Hazard,issues);if(string.IsNullOrWhiteSpace(r.SiteName)||string.IsNullOrWhiteSpace(r.Cue))Add(issues,InfernalFirstExpansionContentValidationIssue.CueInvalid);var expected=Expected(r.LayoutId,r.SocketId);if(expected!=null){if(!FactsMatch(r,expected))Add(issues,InfernalFirstExpansionContentValidationIssue.ExactFactsMismatch);if(SameHostilePlacements(r.Hostiles,expected.Hostiles)&&!HostilesMatch(r.Hostiles,expected.Hostiles))Add(issues,InfernalFirstExpansionContentValidationIssue.HostileOrderMismatch);}}
        private static void ValidateHostiles(IReadOnlyList<InfernalExpansionHostilePlacement> hostiles,ICollection<InfernalFirstExpansionContentValidationIssue> issues){if(hostiles==null||hostiles.Count==0||hostiles.Count>2)Add(issues,InfernalFirstExpansionContentValidationIssue.HostileCardinalityInvalid);if(hostiles==null)return;foreach(var h in hostiles){if(h==null){Add(issues,InfernalFirstExpansionContentValidationIssue.HostileMissing);continue;}if(!string.Equals(h.ContentId,StarterInfernalRaidPacingCatalogue.HellhoundArchetypeId,StringComparison.Ordinal)&&!string.Equals(h.ContentId,StarterInfernalRaidPacingCatalogue.InfernalBruteArchetypeId,StringComparison.Ordinal))Add(issues,InfernalFirstExpansionContentValidationIssue.HostileContentUnsupported);if(!Offset(h.LocalX,h.LocalZ))Add(issues,InfernalFirstExpansionContentValidationIssue.HostileOffsetInvalid);}}
        private static void ValidateHazard(InfernalExpansionHazardPlacement h,ICollection<InfernalFirstExpansionContentValidationIssue> issues){if(h==null)return;if(!string.Equals(h.ContentId,StarterInfernalRaidPacingCatalogue.FlameTrapContentId,StringComparison.Ordinal))Add(issues,InfernalFirstExpansionContentValidationIssue.HazardContentUnsupported);if(!Offset(h.LocalX,h.LocalZ))Add(issues,InfernalFirstExpansionContentValidationIssue.HazardOffsetInvalid);if(!h.IsBypassable||!h.IsNonBlocking)Add(issues,InfernalFirstExpansionContentValidationIssue.HazardSemanticsInvalid);}
        private static bool FactsMatch(InfernalFirstExpansionContentRecipe a,InfernalFirstExpansionContentRecipe b){return string.Equals(a.SourceNodeId,b.SourceNodeId,StringComparison.Ordinal)&&string.Equals(a.SiteId,b.SiteId,StringComparison.Ordinal)&&string.Equals(a.SiteName,b.SiteName,StringComparison.Ordinal)&&string.Equals(a.SiteSignature,b.SiteSignature,StringComparison.Ordinal)&&string.Equals(a.Cue,b.Cue,StringComparison.Ordinal)&&HazardMatch(a.Hazard,b.Hazard)&&HostilesMatch(a.Hostiles,b.Hostiles);}
        private static bool HostilesMatch(IReadOnlyList<InfernalExpansionHostilePlacement> a,IReadOnlyList<InfernalExpansionHostilePlacement>b){if(a==null||b==null||a.Count!=b.Count)return false;for(var i=0;i<a.Count;i++)if(!SamePlacement(a[i],b[i]))return false;return true;}
        private static bool SameHostilePlacements(IReadOnlyList<InfernalExpansionHostilePlacement> a,IReadOnlyList<InfernalExpansionHostilePlacement>b){if(a==null||b==null||a.Count!=b.Count)return false;var remaining=new List<InfernalExpansionHostilePlacement>(b);foreach(var placement in a){var found=-1;for(var i=0;i<remaining.Count;i++)if(SamePlacement(placement,remaining[i])){found=i;break;}if(found<0)return false;remaining.RemoveAt(found);}return true;}
        private static bool SamePlacement(InfernalExpansionHostilePlacement a,InfernalExpansionHostilePlacement b){return a!=null&&b!=null&&string.Equals(a.ContentId,b.ContentId,StringComparison.Ordinal)&&a.LocalX==b.LocalX&&a.LocalZ==b.LocalZ;}
        private static bool HazardMatch(InfernalExpansionHazardPlacement a,InfernalExpansionHazardPlacement b){if(a==null||b==null)return a==b;return string.Equals(a.ContentId,b.ContentId,StringComparison.Ordinal)&&a.LocalX==b.LocalX&&a.LocalZ==b.LocalZ&&a.IsBypassable==b.IsBypassable&&a.IsNonBlocking==b.IsNonBlocking;}
        private static InfernalFirstExpansionContentRecipe Expected(string layout,string socket){foreach(var r in All)if(Matches(r,layout,socket))return r;return null;}private static bool Matches(InfernalFirstExpansionContentRecipe r,string layout,string socket){return string.Equals(r.LayoutId,layout,StringComparison.Ordinal)&&string.Equals(r.SocketId,socket,StringComparison.Ordinal);}private static bool Contains(RealmLayoutGraph layout,string socket){foreach(var s in layout.ExpansionSockets)if(s!=null&&string.Equals(s.SocketId,socket,StringComparison.Ordinal))return true;return false;}private static bool Offset(float x,float z){return !float.IsNaN(x)&&!float.IsInfinity(x)&&!float.IsNaN(z)&&!float.IsInfinity(z)&&Math.Abs(x)<=MaximumAbsoluteOffset&&Math.Abs(z)<=MaximumAbsoluteOffset;}private static bool Stable(string s){if(string.IsNullOrEmpty(s)||!Alpha(s[0])||!Alpha(s[s.Length-1]))return false;for(var i=1;i<s.Length-1;i++)if(!Alpha(s[i])&&s[i]!='.'&&s[i]!='_'&&s[i]!='-')return false;return true;}private static bool Alpha(char c){return c>='a'&&c<='z'||c>='0'&&c<='9';}private static void Valid(string s,InfernalFirstExpansionContentValidationIssue issue,ICollection<InfernalFirstExpansionContentValidationIssue> issues){if(!Stable(s))Add(issues,issue);}private static void Add(ICollection<InfernalFirstExpansionContentValidationIssue> issues,InfernalFirstExpansionContentValidationIssue issue){if(!issues.Contains(issue))issues.Add(issue);}private static InfernalFirstExpansionContentLookupResult Reject(InfernalFirstExpansionContentLookupStatus s){return new InfernalFirstExpansionContentLookupResult(s,null);}private static InfernalFirstExpansionContentRecipe Recipe(string l,string so,string n,string id,string name,string sig,IReadOnlyList<InfernalExpansionHostilePlacement> h,InfernalExpansionHazardPlacement z,string c){return new InfernalFirstExpansionContentRecipe(l,so,n,id,name,sig,h,z,c);}private static InfernalExpansionHostilePlacement Hostile(string id,float x,float z){return new InfernalExpansionHostilePlacement(id,x,z);}private static InfernalExpansionHazardPlacement Hazard(string id,float x,float z,bool b,bool n){return new InfernalExpansionHazardPlacement(id,x,z,b,n);}
    }
}
